### ISSUE TITLE
CORS issues

### ISSUE THREAD

**Issue by Fidel-C** [sinisaos/piccolo-vue-starter#1]
I've used this particular setup of CORS on my Vue app with Fastapi and Piccolo that has only one Fastapi instance, just as shown in the vue example project , but I keep getting CORS errors.

The vue app in my case is on http://localhost:9000.

**Comment by sinisaos** [comment]
@Fidel-C You need to add `http://localhost:9000` (or any other address of your Vue application) to origins
https://github.com/sinisaos/piccolo-vue-starter/blob/dc2ca92d930650350167c354c8440e5066f1dd11/backend/app.py#L34-L36

More info in FastAPI [docs](https://fastapi.tiangolo.com/tutorial/cors/#use-corsmiddleware)

**Comment by Fidel-C** [comment]
I even added it this way
origins= ["http://localhost", "http://localhost:9000", "http://localhost:8080"]
The vue app is actually on http://localhost:9000


I've been battling with this for almost days

**Comment by Fidel-C** [comment]
@sinisaos thanks I just observed that the CORS error goes away once I've internet connection.  Because the backend is expected to make an API call to an external sever which relies on internet connection. I'm just surprised because that shouldn't be throwing CORS errors in the front-end.

**Comment by sinisaos** [comment]
@Fidel-C I just tried and for me the Vue app works on port 8080 or 9000 without problems. This is not a PWA app and you need an internet connection to communicate between the interface and the backend. If this solved your problem, can you please close the issue.
