### ISSUE TITLE
Adding Tables from Multiple Apps to Admin Panel

### ISSUE THREAD

**Issue by Fidel-C** [sinisaos/piccolo-vue-starter#2]
My piccolo FastApi project has three apps, home, accounts and flights.
Each app has a table_finder function that imports all tables from the tables.py file.

I've been unable to add all tables from all the apps to  the root app.py create_admin(
tables=
)
The tables parameter seems to only accept one app's tables.py.  Trying add tables of more than one app
as in

create_admin(
tables=[] 
)

or create_admin(
tables=()
)

throws errors

**Comment by sinisaos** [comment]
> My piccolo FastApi project has three apps, home, accounts and flights. Each app has a table_finder function that imports all tables from the tables.py file.
> 
> I've been unable to add all tables from all the apps to the root app.py create_admin( tables= ) The tables parameter seems to only accept one app's tables.py. Trying add tables of more than one app as in
> 

I can't reproduce your problem. You have to import the table from app like this 
```python
from home.tables import Task
from flight.tables import Flight
from accounts.tables import User

app = FastAPI(
    routes=[
        Mount(
            "/admin/",
            create_admin(
                tables=[Task, Flight, User],
            ),
        ),
```
and everything works as it should.
> create_admin( tables=[] )
> 
> or create_admin( tables=() )
> 
> throws errors

`create_admin` argument `tables` is `list` type not `tuple` and that's the way you get error. 
Hope this helps.

**Comment by Fidel-C** [comment]
Alright thanks a lot. I guess I've to bypass the table_finder helper function to be able to do this. Because the table finder_finder returns a list of tables so when it's from multiple apps it becomes a list of lists as in , tables=[]

**Comment by sinisaos** [comment]
No problem, can you please close the issue.

**Comment by Fidel-C** [comment]
Rather than import the tables manually what I've now done is to unpack each app list this way

tables=[
*app_a.table_classes, *app_b.table_classes, *app_c.table_classes
]

Thanks for your help.
